CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS details (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    manager VARCHAR(100),
    superior VARCHAR(100),
    department VARCHAR(50),
    phoneNumber VARCHAR(20),
    jobTitle VARCHAR(100),
    division VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS purchase_request (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    request_by character varying(255) NOT NULL,
    request_date date NOT NULL,
    customer_name character varying(255) NOT NULL,
    requisition_no character varying(255) NOT NULL,
    online_purchase character varying(255) NOT NULL,
    quotation_no character varying(255) NOT NULL,
    pr_type character varying(30) NOT NULL,
    project_category character varying(255) NOT NULL,
    type_for_purchase character varying(30) NOT NULL,
    customer_po character varying(255) NOT NULL,
    supplier_name character varying(255) NOT NULL,
    project_description text NOT NULL,
    supplier_type character varying(20) NOT NULL,
    item integer NOT NULL,
    description text NOT NULL,
    part_no text,
    brand character varying(255) NOT NULL,
    date_required date NOT NULL,
    quantity integer NOT NULL,
    currency character varying(20) NOT NULL,
    unit_price numeric NOT NULL,
    total_price numeric NOT NULL,
    internal_use text,
    purchase_department text,
    delivery_term text,
    lead_time text,
    tax numeric,
    exwork text,
    pr_count integer DEFAULT 1,
    last_submission_date date,
)